#include "gpio.h"

void GPIO_Init_All(void) {
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_AFIOEN;

    // DHT11 (PA1) - 推挽输出
    GPIOA->CRL &= ~(GPIO_CRL_CNF1 | GPIO_CRL_MODE1);
    GPIOA->CRL |= GPIO_CRL_MODE1_1;

    // 继电器 (PB5) - 推挽输出
    GPIOB->CRL &= ~(GPIO_CRL_CNF5 | GPIO_CRL_MODE5);
    GPIOB->CRL |= GPIO_CRL_MODE5_1;
    GPIOB->BRR = RELAY_PIN;

    // 蜂鸣器 (PB2) - 推挽输出
    GPIOB->CRL &= ~(GPIO_CRL_CNF2 | GPIO_CRL_MODE2);
    GPIOB->CRL |= GPIO_CRL_MODE2_1;
    GPIOB->BRR = BUZZER_PIN;

    // 按键1 (PA8) - 上拉输入
    GPIOA->CRH &= ~(GPIO_CRH_CNF8 | GPIO_CRH_MODE8);
    GPIOA->CRH |= GPIO_CRH_CNF8_1;
    GPIOA->BSRR = KEY1_PIN;

    // 按键2 (PA11) - 上拉输入
    GPIOA->CRH &= ~(GPIO_CRH_CNF11 | GPIO_CRH_MODE11);
    GPIOA->CRH |= GPIO_CRH_CNF11_1;
    GPIOA->BSRR = KEY2_PIN;

    // I2C引脚 (PA15-SDA, PA14-SCL) - 开漏输出
    GPIOA->CRH &= ~(GPIO_CRH_CNF15 | GPIO_CRH_MODE15);
    GPIOA->CRH |= GPIO_CRH_CNF15_0 | GPIO_CRH_MODE15_1;
    GPIOA->CRH &= ~(GPIO_CRH_CNF14 | GPIO_CRH_MODE14);
    GPIOA->CRH |= GPIO_CRH_CNF14_0 | GPIO_CRH_MODE14_1;
    GPIOA->BSRR = I2C_SDA_PIN | I2C_SCL_PIN;
}
