#include "tim.h"

// 禁用JTAG，保留SWD调试功能
void DisableJTAG(void) {
    RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
    // 设置为SW-DP模式，禁用JTAG，释放PB3/PB4/PA15引脚
    AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;
}

void TIM_Init_All(void) {
    // 先禁用JTAG，释放PB3引脚
    DisableJTAG();

    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN | RCC_APB1ENR_TIM4EN;
    RCC->APB2ENR |= RCC_APB2ENR_IOPBEN | RCC_APB2ENR_AFIOEN;

    // PB3配置为复用推挽输出 (TIM2_CH2)
    GPIOB->CRL &= ~(GPIO_CRL_CNF3 | GPIO_CRL_MODE3);
    GPIOB->CRL |= GPIO_CRL_CNF3_1 | GPIO_CRL_MODE3_1;

    // PB8, PB9配置为复用推挽输出 (TIM4_CH3, TIM4_CH4)
    GPIOB->CRH &= ~(GPIO_CRH_CNF8 | GPIO_CRH_MODE8);
    GPIOB->CRH |= GPIO_CRH_CNF8_1 | GPIO_CRH_MODE8_1;
    GPIOB->CRH &= ~(GPIO_CRH_CNF9 | GPIO_CRH_MODE9);
    GPIOB->CRH |= GPIO_CRH_CNF9_1 | GPIO_CRH_MODE9_1;

    // TIM2配置: 50Hz PWM (20ms周期)
    TIM2->PSC = 72 - 1;          // 72MHz / 72 = 1MHz
    TIM2->ARR = 20000 - 1;       // 1MHz / 20000 = 50Hz
    TIM2->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2PE;
    TIM2->CCER |= TIM_CCER_CC2E;
    TIM2->CR1 |= TIM_CR1_CEN;

    // TIM4配置: 50Hz PWM (20ms周期)
    TIM4->PSC = 72 - 1;
    TIM4->ARR = 20000 - 1;
    TIM4->CCMR2 |= TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3PE;
    TIM4->CCMR2 |= TIM_CCMR2_OC4M_2 | TIM_CCMR2_OC4M_1 | TIM_CCMR2_OC4PE;
    TIM4->CCER |= TIM_CCER_CC3E | TIM_CCER_CC4E;
    TIM4->CR1 |= TIM_CR1_CEN;
}
